/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-05-18 02:58:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.groupware.dto.EmployeeDTO;
import com.groupware.dao.EmployeeDAO;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.groupware.dto.EmployeeDTO");
    _jspx_imports_classes.add("com.groupware.dao.EmployeeDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	EmployeeDTO loginEmp = (EmployeeDTO) session.getAttribute("loginEmp");
	if (loginEmp == null) {
		response.sendRedirect("index.jsp");
		return;
	}
	
	List<EmployeeDTO> empList = (List<EmployeeDTO>) request.getAttribute("reserveList");
	
	// 데이터 가져오기
    EmployeeDAO resDao = new EmployeeDAO();
    List<EmployeeDTO> reserveList = resDao.getAllEmployees();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>사내 시스템 - 사원 관리</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/admin.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"page-header\">\r\n");
      out.write("			<h2>전사 직원 관리 (마스터)</h2>\r\n");
      out.write("			<a href=\"main.jsp\" class=\"btn-back\">시스템 메인으로</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"table-wrapper\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>사원 번호</th>\r\n");
      out.write("						<th>성명</th>\r\n");
      out.write("						<th>권한 레벨 조정</th>\r\n");
      out.write("						<th>시스템 권한</th>\r\n");
      out.write("						<th>인사 관리 (위임/퇴사)</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("			\r\n");
      out.write("					 	");

					        // 위쪽 선언부에서 가져온 reserveList 사용
					        if (reserveList != null && !reserveList.isEmpty()) {
					            for (EmployeeDTO emp : reserveList) {
					                // 퇴사자 여부 판별 (예: retired 컬럼/상태값 확인)
					                // Retired 컬럼에서 Y인경우는 퇴사지 N인 경우는 근무자
					                boolean isRetired = "Y".equals(emp.getRetired()); 
					              
					                if(isRetired) 
					                	continue;
					    
      out.write("\r\n");
      out.write("					        	<tr ");
      out.print( isRetired ? "style='opacity: 0.6; background-color: #f8f9fa;'" : "" );
      out.write("> 					        \r\n");
      out.write("					            <!-- 1. 사원 번호 -->\r\n");
      out.write("					            <td style=\"color: #6c757d;\">");
      out.print( emp.getEmpNo() );
      out.write("</td>\r\n");
      out.write("					            \r\n");
      out.write("					            <!-- 2. 성명 -->\r\n");
      out.write("					            <td style=\"font-weight: 600; color: ");
      out.print( isRetired ? "#adb5bd" : "#343a40" );
      out.write(";\">\r\n");
      out.write("					                ");
      out.print( emp.getEmpName() );
      out.write("\r\n");
      out.write("					            </td>\r\n");
      out.write("					\r\n");
      out.write("					            <!-- 3. 권한 레벨 조정 -->\r\n");
      out.write("					            <td>\r\n");
      out.write("					                ");
 if (isRetired) { 
      out.write("\r\n");
      out.write("					                    <span style=\"color: #dc3545; font-weight: bold; font-size: 13px;\">퇴사 처리됨</span>\r\n");
      out.write("					                ");
 } else { 
      out.write("\r\n");
      out.write("					                    <form action=\"adminAction.do\" method=\"post\" style=\"margin: 0; display: flex; justify-content: center; gap: 5px; align-items: center;\">\r\n");
      out.write("					                        <input type=\"hidden\" name=\"action\" value=\"updateLevel\">\r\n");
      out.write("					                        <input type=\"hidden\" name=\"empNo\" value=\"");
      out.print( emp.getEmpNo() );
      out.write("\">\r\n");
      out.write("					                        <select name=\"newLevel\">\r\n");
      out.write("					                            <option value=\"1\" ");
      out.print( emp.getEmpLevel() == 1 ? "selected" : "" );
      out.write(">1단계 (일반)</option>\r\n");
      out.write("					                            <option value=\"2\" ");
      out.print( emp.getEmpLevel() == 2 ? "selected" : "" );
      out.write(">2단계</option>\r\n");
      out.write("					                            <option value=\"3\" ");
      out.print( emp.getEmpLevel() == 3 ? "selected" : "" );
      out.write(">3단계</option>\r\n");
      out.write("					                            <option value=\"4\" ");
      out.print( emp.getEmpLevel() == 4 ? "selected" : "" );
      out.write(">4단계 (부서장)</option>\r\n");
      out.write("					                            <option value=\"5\" ");
      out.print( emp.getEmpLevel() == 5 ? "selected" : "" );
      out.write(">5단계 (임원)</option>\r\n");
      out.write("					                        </select>\r\n");
      out.write("					                        <button type=\"submit\" class=\"btn-action btn-update\">수정</button>\r\n");
      out.write("					                    </form>\r\n");
      out.write("					                ");
 } 
      out.write("\r\n");
      out.write("					            </td>\r\n");
      out.write("					\r\n");
      out.write("					            <!-- 4. 시스템 권한 (최고관리자 여부) -->\r\n");
      out.write("					            <td>\r\n");
      out.write("					                ");
 if (isRetired) { 
      out.write("\r\n");
      out.write("					                    <span class=\"badge-retired\" style=\"color: #999;\">접근불가</span>\r\n");
      out.write("					                ");
 } else if ("Y".equals(emp.getManager())) { 
      out.write("\r\n");
      out.write("					                    <span class=\"badge-manager\" style=\"color: #007bff; font-weight: bold;\">최고 관리자</span>\r\n");
      out.write("					                ");
 } else { 
      out.write("\r\n");
      out.write("					                    <span class=\"badge-normal\">일반 사원</span>\r\n");
      out.write("					                ");
 } 
      out.write("\r\n");
      out.write("					            </td>\r\n");
      out.write("					\r\n");
      out.write("					            <!-- 5. 인사 관리 (위임/퇴사) -->\r\n");
      out.write("					            <td>\r\n");
      out.write("					                ");
 if (isRetired) { 
      out.write("\r\n");
      out.write("					                    <span style=\"color: #adb5bd; font-size: 13px;\">-</span>\r\n");
      out.write("					                ");
 } else if (loginEmp != null && emp.getEmpNo() != loginEmp.getEmpNo()) { 
      out.write("\r\n");
      out.write("					                    <form action=\"adminAction.do\" method=\"post\" style=\"display: inline;\">\r\n");
      out.write("					                        <input type=\"hidden\" name=\"action\" value=\"transferManager\">\r\n");
      out.write("					                        <input type=\"hidden\" name=\"empNo\" value=\"");
      out.print( emp.getEmpNo() );
      out.write("\">\r\n");
      out.write("					                        <button type=\"submit\" class=\"btn-action btn-transfer\" \r\n");
      out.write("					                                onclick=\"return confirm('관리자 권한을 위임하시겠습니까?');\">위임</button>\r\n");
      out.write("					                    </form>\r\n");
      out.write("					\r\n");
      out.write("					                    <form action=\"adminAction.do\" method=\"post\" style=\"display: inline;\">\r\n");
      out.write("					                        <input type=\"hidden\" name=\"action\" value=\"deleteEmp\">\r\n");
      out.write("					                        <input type=\"hidden\" name=\"empNo\" value=\"");
      out.print( emp.getEmpNo() );
      out.write("\">\r\n");
      out.write("					                        <button type=\"submit\" class=\"btn-action btn-delete\" \r\n");
      out.write("					                                onclick=\"return confirm('해당 사원을 퇴사 처리하시겠습니까?');\">퇴사</button>\r\n");
      out.write("					                    </form>\r\n");
      out.write("					                ");
 } else { 
      out.write("\r\n");
      out.write("					                    <span style=\"color: #007bff; font-size: 12px; font-weight: bold;\">본인(마스터)</span>\r\n");
      out.write("					                ");
 } 
      out.write("\r\n");
      out.write("					            </td>\r\n");
      out.write("					        </tr>\r\n");
      out.write("					    ");
 
					            } // for end
					        } else { 
					    
      out.write("\r\n");
      out.write("					        <tr>\r\n");
      out.write("					            <td colspan=\"5\" style=\"text-align: center; padding: 20px;\">등록된 사원이 없습니다.</td>\r\n");
      out.write("					        </tr>\r\n");
      out.write("					    ");
 } 
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<br>\r\n");
      out.write("		<!-- 관리자 사원 등록 폼 영역 -->\r\n");
      out.write("		<div class=\"insert-box\"\r\n");
      out.write("			style=\"background-color: #ffffff; padding: 25px; border-radius: 6px; margin-bottom: 30px; border: 1px solid #e9ecef; border-left: 4px solid #343a40;\">\r\n");
      out.write("			<h3 style=\"margin-top: 0;\">신규 사원 사전 등록 (초기 세팅)</h3>\r\n");
      out.write("			<form action=\"insertEmp.do\" method=\"post\"\r\n");
      out.write("				style=\"display: flex; gap: 10px; align-items: center;\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 사번 입력 (DB에서 PK 역할) -->\r\n");
      out.write("				<input type=\"number\" name=\"empNo\" placeholder=\"사번 (숫자)\" required\r\n");
      out.write("					style=\"padding: 10px; border: 1px solid #ced4da; border-radius: 4px; width: 120px;\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 사원명 입력 -->\r\n");
      out.write("				<input type=\"text\" name=\"empName\" placeholder=\"사원 성명\" required\r\n");
      out.write("					style=\"padding: 10px; border: 1px solid #ced4da; border-radius: 4px; flex: 1;\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 직급 선택 -->\r\n");
      out.write("				<select name=\"empLevel\" required\r\n");
      out.write("					style=\"padding: 10px; border: 1px solid #ced4da; border-radius: 4px;\">\r\n");
      out.write("					<option value=\"1\">1단계 (일반 사원)</option>\r\n");
      out.write("					<option value=\"2\">2단계 (대리)</option>\r\n");
      out.write("					<option value=\"3\">3단계 (과장)</option>\r\n");
      out.write("					<option value=\"4\">4단계 (차장)</option>\r\n");
      out.write("					<option value=\"5\">5단계 (대표/임원)</option>\r\n");
      out.write("				</select>\r\n");
      out.write("\r\n");
      out.write("				<!-- 관리자 메뉴 접근 권한 -->\r\n");
      out.write("				<select name=\"manager\" required\r\n");
      out.write("					style=\"padding: 10px; border: 1px solid #ced4da; border-radius: 4px;\">\r\n");
      out.write("					<option value=\"N\">일반 권한 (N)</option>\r\n");
      out.write("					<option value=\"Y\">관리자 권한 (Y)</option>\r\n");
      out.write("				</select>\r\n");
      out.write("\r\n");
      out.write("				<button type=\"submit\"\r\n");
      out.write("					style=\"padding: 10px 20px; background-color: #343a40; color: white; border: none; border-radius: 4px; font-weight: bold; cursor: pointer;\">사원\r\n");
      out.write("					등록</button>\r\n");
      out.write("			</form>\r\n");
      out.write("			<p style=\"margin: 10px 0 0 0; font-size: 12px; color: #6c757d;\">*\r\n");
      out.write("				등록 후 해당 사원이 직접 회원가입 메뉴에서 사번을 인증하고 비밀번호를 세팅해야 합니다.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
