/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-05-15 05:43:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.groupware.dto.EmployeeDTO;

public final class adminEqList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.groupware.dto.EmployeeDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	EmployeeDTO loginEmp = (EmployeeDTO) session.getAttribute("loginEmp");
	if (loginEmp == null) {
		response.sendRedirect("index.jsp");
		return;
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>사내 시스템 - 재고 관리</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/adminEqList.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"page-header\">\r\n");
      out.write("        <h2>공용 비품 마스터 데이터 관리</h2>\r\n");
      out.write("        <a href=\"main.jsp\" class=\"btn-back\">시스템 메인으로</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"insert-box\">\r\n");
      out.write("        <h3>신규 비품 등록</h3>\r\n");
      out.write("        <form action=\"insertEq.do\" method=\"post\" style=\"display: flex; gap: 10px; flex: 1;\">\r\n");
      out.write("            <input type=\"text\" name=\"eqName\" placeholder=\"비품 명칭 입력\" required style=\"flex: 1;\">\r\n");
      out.write("            <input type=\"number\" name=\"totalCount\" placeholder=\"초기 총 수량\" required style=\"width: 120px;\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn-submit\">DB 등록</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"table-wrapper\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>관리 번호</th>\r\n");
      out.write("                    <th>비품 명칭</th>\r\n");
      out.write("                    <th>보유 총 수량</th>\r\n");
      out.write("                    <th>대여 가능 수량</th>\r\n");
      out.write("                    <th>데이터 관리</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal-overlay\" id=\"modalOverlay\" onclick=\"closeUpdateModal()\"></div>\r\n");
      out.write("<div id=\"updateModal\">\r\n");
      out.write("    <h3>비품 정보 수정</h3>\r\n");
      out.write("    <form action=\"updateEq.do\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\" name=\"eqNo\" id=\"upEqNo\">\r\n");
      out.write("        <div class=\"update-group\">\r\n");
      out.write("            <label>비품 명칭</label>\r\n");
      out.write("            <input type=\"text\" name=\"eqName\" id=\"upEqName\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"update-group\">\r\n");
      out.write("            <label>보유 총 수량</label>\r\n");
      out.write("            <input type=\"number\" name=\"totalCount\" id=\"upTotalCount\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"update-group\">\r\n");
      out.write("            <label>대여 가능 잔여 수량</label>\r\n");
      out.write("            <input type=\"number\" name=\"remainCount\" id=\"upRemainCount\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-btn-group\">\r\n");
      out.write("            <button type=\"button\" class=\"btn-modal-cancel\" onclick=\"closeUpdateModal()\">취소</button>\r\n");
      out.write("            <button type=\"submit\" class=\"btn-modal-submit\">수정 반영</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form id=\"deleteForm\" action=\"deleteEq.do\" method=\"post\">\r\n");
      out.write("    <input type=\"hidden\" name=\"eqNo\" id=\"delEqNo\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function deleteEquipment(eqNo) {\r\n");
      out.write("        if (confirm(\"해당 비품 데이터를 시스템에서 영구 삭제하시겠습니까?\\n(경고: 현재 사원이 대여 중인 비품은 삭제할 수 없습니다)\")) {\r\n");
      out.write("            document.getElementById(\"delEqNo\").value = eqNo;\r\n");
      out.write("            document.getElementById(\"deleteForm\").submit();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function openUpdateModal(no, name, total, remain) {\r\n");
      out.write("        document.getElementById(\"upEqNo\").value = no;\r\n");
      out.write("        document.getElementById(\"upEqName\").value = name;\r\n");
      out.write("        document.getElementById(\"upTotalCount\").value = total;\r\n");
      out.write("        document.getElementById(\"upRemainCount\").value = remain;\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"updateModal\").style.display = \"block\";\r\n");
      out.write("        document.getElementById(\"modalOverlay\").style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function closeUpdateModal() {\r\n");
      out.write("        document.getElementById(\"updateModal\").style.display = \"none\";\r\n");
      out.write("        document.getElementById(\"modalOverlay\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
