/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-05-15 07:23:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.groupware.dto.RentalHistoryDTO;
import com.groupware.dto.ReservationDTO;
import com.groupware.dto.LeaveHistoryDTO;
import com.groupware.dto.EmployeeDTO;
import com.groupware.dao.ReservationDAO;
import com.groupware.dao.RentalDAO;
import com.groupware.dao.LeaveDAO;
import com.groupware.dao.EmployeeDAO;
import java.time.LocalDateTime;
import java.time.LocalDate;
import java.time.LocalTime;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(16);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.groupware.dto.RentalHistoryDTO");
    _jspx_imports_classes.add("com.groupware.dto.ReservationDTO");
    _jspx_imports_classes.add("com.groupware.dto.LeaveHistoryDTO");
    _jspx_imports_classes.add("com.groupware.dto.EmployeeDTO");
    _jspx_imports_classes.add("com.groupware.dao.ReservationDAO");
    _jspx_imports_classes.add("com.groupware.dao.RentalDAO");
    _jspx_imports_classes.add("com.groupware.dao.LeaveDAO");
    _jspx_imports_classes.add("com.groupware.dao.EmployeeDAO");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.LocalTime");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // 로그인 체크 세션없으면 로그인페이지로 이동
    EmployeeDTO loginEmp = (EmployeeDTO) session.getAttribute("loginEmp");
    if (loginEmp == null) {
        response.sendRedirect("index.jsp");
        return;
    }

    // 실시간 연차 갱신 로직
    EmployeeDAO empDao = new EmployeeDAO();
    EmployeeDTO updatedEmp = empDao.getEmployeeByNo(String.valueOf(loginEmp.getEmpNo()));
    if (updatedEmp != null) {
        session.setAttribute("loginEmp", updatedEmp);
        loginEmp = updatedEmp;
    }

    // 데이터 가져오기
    ReservationDAO resDao = new ReservationDAO();
    List<ReservationDTO> reserveList = resDao.getMyReservations(loginEmp.getEmpNo());

    /* RentalDAO rentalDao = new RentalDAO();
    List<RentalHistoryDTO> myList = rentalDao.getMyRentalList(loginEmp.getEmpNo());

    LeaveDAO leaveDao = new LeaveDAO();
    List<LeaveHistoryDTO> myLeaveList = leaveDao.getMyLeaveList(loginEmp.getEmpNo()); */

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Groupware Dashboard</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/main.css?v=1.5\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    /* function processReturn(rentalNo) { if (confirm(\"반납 처리하시겠습니까?\")) location.href = 'returnProcess.do?rentalNo=' + rentalNo + '&from=main'; } */\r\n");
      out.write("    function cancelReserve(resNo) { if (confirm(\"예약을 취소하시겠습니까?\")) location.href = \"cancelReserve.do?resNo=\" + resNo + '&from=main'; }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <div class=\"header-inner\">\r\n");
      out.write("            <a href=\"main.jsp\" class=\"logo-area\">\r\n");
      out.write("                <span class=\"logo-group\">Group</span><span class=\"logo-ware\">Ware</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"nav-buttons\">\r\n");
      out.write("                <span class=\"user-profile-info\">\r\n");
      out.write("                    ");
 if ("Y".equals(loginEmp.getManager())) { 
      out.write("\r\n");
      out.write("                        <span class=\"admin-tag\">ADMIN</span>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <b>");
      out.print(loginEmp.getEmpName());
      out.write("</b>님\r\n");
      out.write("                </span>\r\n");
      out.write("\r\n");
      out.write("                ");
 if ("Y".equals(loginEmp.getManager())) { 
      out.write("\r\n");
      out.write("                    <a href=\"adminEqList.do\" class=\"nav-btn admin-special\">재고 관리</a>\r\n");
      out.write("                    <a href=\"admin.do\" class=\"nav-btn admin-special\">사원 관리</a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <a href=\"officeMap.jsp\" class=\"nav-btn\">오피스 예약</a>\r\n");
      out.write("                <a href=\"leaveForm.do\" class=\"nav-btn\">휴가 신청</a>\r\n");
      out.write("                <a href=\"equipmentList.do\" class=\"nav-btn\">비품 대여 신청</a>\r\n");
      out.write("                <a href=\"documentList.do\" class=\"nav-btn\">기안 문서함</a>\r\n");
      out.write("                <a href=\"myPage.do\" class=\"nav-btn\">마이페이지</a>\r\n");
      out.write("                <a href=\"logout.do\" class=\"nav-btn logout\">로그아웃</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"dashboard-container\">\r\n");
      out.write("        <div class=\"info-card\">\r\n");
      out.write("            <div class=\"welcome-box\">\r\n");
      out.write("                <h3>안녕하세요, <b>");
      out.print(loginEmp.getEmpName());
      out.write("</b>님!</h3>\r\n");
      out.write("                <p>");
      out.print(loginEmp.getDept());
      out.write(" 소속</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"leave-box\">\r\n");
      out.write("                <p class=\"leave-label\">잔여 연차 현황</p>\r\n");
      out.write("                <div class=\"leave-count\">\r\n");
      out.write("                    <span class=\"current\">");
      out.print(loginEmp.getCurLeave());
      out.write("</span>\r\n");
      out.write("                    <span class=\"divider\">/</span>\r\n");
      out.write("                    <span class=\"total\">");
      out.print(loginEmp.getMaxLeave());
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"section-title\">내 회의실 예약 현황</div>\r\n");
      out.write("        <div class=\"table-wrapper\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead><tr><th>예약 번호</th><th>회의실</th><th>예약 일자</th><th>사용 시간</th><th>사용 목적</th><th>상태</th><th>비고</th></tr></thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                ");
 if (reserveList == null || reserveList.isEmpty()) { 
      out.write("\r\n");
      out.write("                    <tr><td colspan=\"7\" class=\"empty-data\">예약 내역이 없습니다.</td></tr>\r\n");
      out.write("                ");
 } else { for (ReservationDTO dto : reserveList) {
                    String displayStatus = dto.getStatus(); String statusClass = "status-blue";
                    if ("예약완료".equals(displayStatus)) {
                        try {
                            LocalDateTime endDateTime = LocalDateTime.of(((java.sql.Date) dto.getResDate()).toLocalDate(), LocalTime.parse(dto.getEndTime()));
                            if (LocalDateTime.now().isAfter(endDateTime)) { displayStatus = "이용 종료"; statusClass = "status-gray"; }
                        } catch (Exception e) {}
                    } else if ("취소됨".equals(displayStatus)) { statusClass = "status-red"; }
                
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print(dto.getResNo());
      out.write("</td>\r\n");
      out.write("                        <td class=\"emphasize\">");
      out.print(dto.getRoomId());
      out.write("호</td>\r\n");
      out.write("                        <td>");
      out.print(dto.getResDate());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(dto.getStartTime());
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print(dto.getEndTime());
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(dto.getPurpose());
      out.write("</td>\r\n");
      out.write("                        <td><span class=\"status-badge ");
      out.print(statusClass);
      out.write('"');
      out.write('>');
      out.print(displayStatus);
      out.write("</span></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            ");
 if ("예약완료".equals(displayStatus)) { 
      out.write("\r\n");
      out.write("                                <button class=\"btn-action btn-cancel\" onclick=\"cancelReserve(");
      out.print(dto.getResNo());
      out.write(")\">예약 취소</button>\r\n");
      out.write("                            ");
 } else { 
      out.write('-');
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                ");
 } } 
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
