/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-05-15 02:17:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.groupware.dto.RentalHistoryDTO;
import com.groupware.dto.ReservationDTO;
import com.groupware.dto.EmployeeDTO;
import java.time.LocalDateTime;
import java.time.LocalDate;
import java.time.LocalTime;
import com.groupware.dto.LeaveHistoryDTO;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.groupware.dto.RentalHistoryDTO");
    _jspx_imports_classes.add("com.groupware.dto.ReservationDTO");
    _jspx_imports_classes.add("com.groupware.dto.EmployeeDTO");
    _jspx_imports_classes.add("java.time.LocalDateTime");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("java.time.LocalTime");
    _jspx_imports_classes.add("com.groupware.dto.LeaveHistoryDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

EmployeeDTO loginEmp = (EmployeeDTO) session.getAttribute("loginEmp");
if (loginEmp == null) {
	response.sendRedirect("index.jsp");
	return;
}
List<ReservationDTO> reserveList = (List<ReservationDTO>) request.getAttribute("reserveList");
/* List<RentalHistoryDTO> myList = (List<RentalHistoryDTO>) request.getAttribute("myList");
List<LeaveHistoryDTO> leaveList = (List<LeaveHistoryDTO>) request.getAttribute("leaveList"); */ // ★ 컨트롤러에서 보내준 데이터

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>사내 시스템 - 마이페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/myPage.css\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    /* function processReturn(rentalNo) {\r\n");
      out.write("        if (confirm(\"해당 비품을 반납 처리하시겠습니까?\")) {\r\n");
      out.write("            location.href = 'returnProcess.do?rentalNo=' + rentalNo + '&from=mypage';\r\n");
      out.write("        }\r\n");
      out.write("    } */\r\n");
      out.write("    function cancelReserve(resNo) {\r\n");
      out.write("        if (confirm(\"정말 이 예약을 취소하시겠습니까?\")) {\r\n");
      out.write("            location.href = \"cancelReserve.do?resNo=\" + resNo + '&from=mypage';\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"page-header\">\r\n");
      out.write("			<h2>마이페이지</h2>\r\n");
      out.write("			<div class=\"btn-group\">\r\n");
      out.write("				<a href=\"changePw.jsp\" class=\"btn-pw\">비밀번호 변경</a> <a href=\"main.jsp\"\r\n");
      out.write("					class=\"btn-main\">시스템 메인으로</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"section-title\">내 회의실 예약 현황</div>\r\n");
      out.write("		<div class=\"table-wrapper\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>예약 번호</th>\r\n");
      out.write("						<th>회의실</th>\r\n");
      out.write("						<th>예약 일자</th>\r\n");
      out.write("						<th>사용 시간</th>\r\n");
      out.write("						<th>사용 목적</th>\r\n");
      out.write("						<th>상태</th>\r\n");
      out.write("						<th>비고</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					");

					if (reserveList == null || reserveList.isEmpty()) {
					
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"7\" style=\"padding: 40px; color: #6c757d;\">예약 내역이\r\n");
      out.write("							없습니다.</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

					} else {
					for (ReservationDTO dto : reserveList) {
						String displayStatus = dto.getStatus();
						String statusClass = "bg-primary";

						// ★ 추가된 로직: 현재 DB상 '예약완료'여도, 현재 시간이 종료 시간을 넘었는지 실시간 확인
						if ("예약완료".equals(displayStatus)) {
							try {
						LocalDate rDate = ((java.sql.Date) dto.getResDate()).toLocalDate();
						LocalTime eTime = LocalTime.parse(dto.getEndTime());
						LocalDateTime endDateTime = LocalDateTime.of(rDate, eTime);

						// 현재 시간이 종료 시간보다 미래일 경우
						if (LocalDateTime.now().isAfter(endDateTime)) {
							displayStatus = "이용 종료";
							statusClass = "bg-secondary"; // 이용 종료는 회색 배지
						}
							} catch (Exception e) {
						// 날짜 파싱 오류 대비
							}
						} else if ("취소됨".equals(displayStatus)) {
							statusClass = "bg-danger";
						}
					
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td style=\"color: #6c757d;\">");
      out.print(dto.getResNo());
      out.write("</td>\r\n");
      out.write("						<td style=\"font-weight: 600; color: #343a40;\">");
      out.print(dto.getRoomId());
      out.write("호</td>\r\n");
      out.write("						<td>");
      out.print(dto.getResDate());
      out.write("</td>\r\n");
      out.write("						<td>");
      out.print(dto.getStartTime());
      out.write(' ');
      out.write('~');
      out.write(' ');
      out.print(dto.getEndTime());
      out.write("</td>\r\n");
      out.write("						<td>");
      out.print(dto.getPurpose());
      out.write("</td>\r\n");
      out.write("						<td><span class=\"status-badge ");
      out.print(statusClass);
      out.write('"');
      out.write('>');
      out.print(displayStatus);
      out.write("</span></td>\r\n");
      out.write("						<td>\r\n");
      out.write("							<!-- ★ 수정된 로직: 실시간 상태가 '예약완료'일 때만 예약 취소 버튼을 노출 --> ");

 if ("예약완료".equals(displayStatus)) {
 
      out.write("\r\n");
      out.write("							<button class=\"btn-action btn-cancel\"\r\n");
      out.write("								onclick=\"cancelReserve(");
      out.print(dto.getResNo());
      out.write(")\">예약 취소</button> ");

 } else {
 
      out.write(" <span style=\"color: #ced4da;\">-</span> ");

 }
 
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

					}
					}
					
      out.write("\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<!-- 3. 내 휴가 신청 현황 (새로 추가) -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
