/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-05-15 07:23:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.groupware.dto.EmployeeDTO;

public final class officeMap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.groupware.dto.EmployeeDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

EmployeeDTO loginEmp = (EmployeeDTO) session.getAttribute("loginEmp");
if (loginEmp == null) {
	response.sendRedirect("index.jsp");
	return;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>사내 시스템 - 오피스 도면 예약</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/officeMap.css?v=3.0\">\r\n");
      out.write("<script>\r\n");
      out.write("    function switchFloor(floor) {\r\n");
      out.write("        for (let i = 4; i <= 5; i++) {\r\n");
      out.write("            document.getElementById('map' + i).style.display = 'none';\r\n");
      out.write("            document.getElementById('tab' + i).classList.remove('active');\r\n");
      out.write("        }\r\n");
      out.write("        document.getElementById('map' + floor).style.display = 'block';\r\n");
      out.write("        document.getElementById('tab' + floor).classList.add('active');\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <div class=\"header-inner\">\r\n");
      out.write("            <a href=\"main.jsp\" class=\"logo-area\">\r\n");
      out.write("                <span class=\"logo-group\">Group</span><span class=\"logo-ware\">Ware</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"nav-buttons\">\r\n");
      out.write("                <span class=\"user-profile-info\">\r\n");
      out.write("                    ");
 if ("Y".equals(loginEmp.getManager())) { 
      out.write("\r\n");
      out.write("                        <span class=\"admin-tag\">ADMIN</span>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                    <b>");
      out.print(loginEmp.getEmpName());
      out.write("</b>님\r\n");
      out.write("                </span>\r\n");
      out.write("\r\n");
      out.write("                ");
 if ("Y".equals(loginEmp.getManager())) { 
      out.write("\r\n");
      out.write("                    <a href=\"adminEqList.do\" class=\"nav-btn admin-special\">재고 관리</a>\r\n");
      out.write("                    <a href=\"admin.do\" class=\"nav-btn admin-special\">사원 관리</a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"officeMap.jsp\" class=\"nav-btn active-page\">오피스 예약</a>\r\n");
      out.write("                <a href=\"leaveForm.do\" class=\"nav-btn\">휴가 신청</a>\r\n");
      out.write("                <a href=\"equipmentList.do\" class=\"nav-btn\">비품 대여 신청</a>\r\n");
      out.write("                <a href=\"documentList.do\" class=\"nav-btn\">기안 문서함</a>	\r\n");
      out.write("                <a href=\"myPage.do\" class=\"nav-btn\">마이페이지</a>\r\n");
      out.write("                <a href=\"logout.do\" class=\"nav-btn logout\">로그아웃</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"dashboard-container\">\r\n");
      out.write("        <div class=\"map-wrapper\">\r\n");
      out.write("            <div class=\"reservation-header\">\r\n");
      out.write("                <h3>오피스 예약</h3>\r\n");
      out.write("                <p>예약을 진행하실 층수와 회의실을 도면에서 선택해 주세요.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"floor-tabs\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <button class=\"floor-tab active\" id=\"tab4\" onclick=\"switchFloor(4)\">4층</button>\r\n");
      out.write("                <button class=\"floor-tab\" id=\"tab5\" onclick=\"switchFloor(5)\">5층</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"map4\" class=\"map-container\">\r\n");
      out.write("                <div class=\"room-btn\" id=\"room404\" onclick=\"location.href='reserve.do?roomId=404'\"></div>\r\n");
      out.write("                <div class=\"room-btn\" id=\"room403\" onclick=\"location.href='reserve.do?roomId=403'\"></div>\r\n");
      out.write("                <div class=\"room-btn\" id=\"room402\" onclick=\"location.href='reserve.do?roomId=402'\"></div>\r\n");
      out.write("                <div class=\"room-btn\" id=\"room401\" onclick=\"location.href='reserve.do?roomId=401'\"></div>\r\n");
      out.write("                <div class=\"room-btn\" id=\"roomInterview\" onclick=\"location.href='reserve.do?roomId=Interview'\"></div>\r\n");
      out.write("                <div class=\"room-btn\" id=\"roomConsult\" onclick=\"location.href='reserve.do?roomId=Consult'\"></div>\r\n");
      out.write("                <div class=\"room-btn\" id=\"roomMeeting\" onclick=\"location.href='reserve.do?roomId=Meeting'\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"map5\" class=\"map-container\">\r\n");
      out.write("                <div class=\"room-btn\" id=\"room503\" onclick=\"location.href='reserve.do?roomId=503'\"></div>\r\n");
      out.write("                <div class=\"room-btn\" id=\"room502\" onclick=\"location.href='reserve.do?roomId=502'\"></div>\r\n");
      out.write("                <div class=\"room-btn\" id=\"room501\" onclick=\"location.href='reserve.do?roomId=501'\"></div>\r\n");
      out.write("                <div class=\"room-btn\" id=\"roomMeeting5\" onclick=\"location.href='reserve.do?roomId=Meeting5'\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
