/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-05-15 06:50:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.groupware.dto.EmployeeDTO;
import com.groupware.dto.RoomDTO;

public final class reserve_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.groupware.dto.EmployeeDTO");
    _jspx_imports_classes.add("com.groupware.dto.RoomDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

EmployeeDTO loginEmp = (EmployeeDTO) session.getAttribute("loginEmp");
if (loginEmp == null) {
	response.sendRedirect("index.jsp");
	return;
}

RoomDTO roomInfo = (RoomDTO) request.getAttribute("roomInfo");
if (roomInfo == null) {
	response.sendRedirect("main.jsp");
	return;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>사내 시스템 - 예약 신청</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/reserve.css\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    let timerInterval = null; \r\n");
      out.write("    let selectedTimes = [];\r\n");
      out.write("\r\n");
      out.write("    function isContinuous(times) {\r\n");
      out.write("        if (times.length <= 1) return true;\r\n");
      out.write("        for (let i = 0; i < times.length - 1; i++) {\r\n");
      out.write("            let t1 = parseInt(times[i].split(':')[0]);\r\n");
      out.write("            let t2 = parseInt(times[i+1].split(':')[0]);\r\n");
      out.write("            if (t2 - t1 !== 1) return false;\r\n");
      out.write("        }\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function startTimer(startStr, endStr) {\r\n");
      out.write("        let timeLeft = 300; // 5분 (테스트용 10초로 변경 가능)\r\n");
      out.write("        const timerBox = document.getElementById(\"timerBox\");\r\n");
      out.write("        const timeDisplay = document.getElementById(\"timeDisplay\");\r\n");
      out.write("        const submitBtn = document.getElementById(\"submitBtn\");\r\n");
      out.write("        const holdBtn = document.getElementById(\"holdBtn\");\r\n");
      out.write("        const holdTimeText = document.getElementById(\"holdTimeText\");\r\n");
      out.write("\r\n");
      out.write("        holdTimeText.innerText = \"[\" + startStr + \" ~ \" + endStr + \"]\";\r\n");
      out.write("\r\n");
      out.write("        timerBox.style.display = \"block\"; \r\n");
      out.write("        submitBtn.disabled = false; // 이때만 예약 확정 버튼이 활성화됨\r\n");
      out.write("        holdBtn.style.display = \"none\"; \r\n");
      out.write("\r\n");
      out.write("        document.querySelectorAll('.time-btn').forEach(btn => btn.disabled = true);\r\n");
      out.write("\r\n");
      out.write("        if(timerInterval) clearInterval(timerInterval);\r\n");
      out.write("        timerInterval = setInterval(function() {\r\n");
      out.write("            timeLeft--;\r\n");
      out.write("            let minutes = Math.floor(timeLeft / 60);\r\n");
      out.write("            let seconds = timeLeft % 60;\r\n");
      out.write("            timeDisplay.textContent = (minutes < 10 ? \"0\" : \"\") + minutes + \":\" + (seconds < 10 ? \"0\" : \"\") + seconds;\r\n");
      out.write("\r\n");
      out.write("            if (timeLeft <= 0) {\r\n");
      out.write("                clearInterval(timerInterval);\r\n");
      out.write("                alert(\"예약 대기 시간이 만료되었습니다. 다시 진행해 주세요.\");\r\n");
      out.write("                location.reload(); \r\n");
      out.write("            }\r\n");
      out.write("        }, 1000);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("        const timeButtons = document.querySelectorAll('.time-btn');\r\n");
      out.write("        const resDateInput = document.getElementById(\"resDate\");\r\n");
      out.write("        const holdBtn = document.getElementById(\"holdBtn\");\r\n");
      out.write("        \r\n");
      out.write("        // ★ 오늘 날짜 구해서 달력(min)에 세팅하기 (과거 날짜 원천 차단)\r\n");
      out.write("        const today = new Date();\r\n");
      out.write("        const todayStr = today.getFullYear() + '-' + String(today.getMonth() + 1).padStart(2, '0') + '-' + String(today.getDate()).padStart(2, '0');\r\n");
      out.write("        resDateInput.setAttribute(\"min\", todayStr);\r\n");
      out.write("        \r\n");
      out.write("        timeButtons.forEach(btn => {\r\n");
      out.write("            btn.addEventListener('click', function() {\r\n");
      out.write("                if(this.disabled) return;\r\n");
      out.write("                const timeStr = this.getAttribute('data-time');\r\n");
      out.write("\r\n");
      out.write("                if (this.classList.contains('active')) {\r\n");
      out.write("                    this.classList.remove('active');\r\n");
      out.write("                    selectedTimes = selectedTimes.filter(t => t !== timeStr);\r\n");
      out.write("                    if (!isContinuous(selectedTimes)) {\r\n");
      out.write("                        alert(\"연속된 시간만 선택 가능합니다.\");\r\n");
      out.write("                        this.classList.add('active');\r\n");
      out.write("                        selectedTimes.push(timeStr);\r\n");
      out.write("                        selectedTimes.sort();\r\n");
      out.write("                    }\r\n");
      out.write("                } else {\r\n");
      out.write("                    selectedTimes.push(timeStr);\r\n");
      out.write("                    selectedTimes.sort();\r\n");
      out.write("                    if (!isContinuous(selectedTimes)) {\r\n");
      out.write("                        alert(\"연속된 시간만 선택 가능합니다.\");\r\n");
      out.write("                        selectedTimes = selectedTimes.filter(t => t !== timeStr);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        this.classList.add('active');\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        holdBtn.addEventListener('click', function() {\r\n");
      out.write("            // ★ JS 이중 차단: HTML을 조작해서 누르더라도 여기서 튕겨냄\r\n");
      out.write("            ");
 boolean isRoomEnableJs = "Y".equals(roomInfo.getEnable()); 
      out.write("\r\n");
      out.write("            ");
 if (!isRoomEnableJs) { 
      out.write("\r\n");
      out.write("                alert(\"현재 점검 중으로 예약이 불가능한 회의실입니다.\");\r\n");
      out.write("                return;\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            const selectedDate = resDateInput.value;\r\n");
      out.write("            if(!selectedDate) { alert(\"예약 일자를 먼저 선택해 주세요.\"); return; }\r\n");
      out.write("            if(selectedTimes.length === 0) { alert(\"예약할 시간을 선택해 주세요.\"); return; }\r\n");
      out.write("\r\n");
      out.write("            const startTime = selectedTimes[0];\r\n");
      out.write("            let lastHour = parseInt(selectedTimes[selectedTimes.length - 1].split(':')[0]);\r\n");
      out.write("            let endTimeStr = (lastHour + 1 < 10 ? '0' + (lastHour + 1) : (lastHour + 1)) + ':00';\r\n");
      out.write("            \r\n");
      out.write("            const roomId = document.getElementById(\"roomId\").value;\r\n");
      out.write("            const empNo = document.getElementById(\"empNo\").value;\r\n");
      out.write("\r\n");
      out.write("            const formData = new URLSearchParams();\r\n");
      out.write("            formData.append(\"roomId\", roomId);\r\n");
      out.write("            formData.append(\"empNo\", empNo);\r\n");
      out.write("            formData.append(\"resDate\", selectedDate);\r\n");
      out.write("            formData.append(\"startTime\", startTime);\r\n");
      out.write("            formData.append(\"endTime\", endTimeStr); \r\n");
      out.write("\r\n");
      out.write("            fetch('holdReserve.do', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\r\n");
      out.write("                body: formData.toString()\r\n");
      out.write("            })\r\n");
      out.write("            .then(response => response.json())\r\n");
      out.write("            .then(data => {\r\n");
      out.write("                if(data.result === 'success') {\r\n");
      out.write("                    document.getElementById('resNo').value = data.resNo;\r\n");
      out.write("                    startTimer(startTime, endTimeStr);\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(\"선택하신 시간에 이미 등록된 예약이 존재합니다. 새로고침 후 다시 시도해 주세요.\");\r\n");
      out.write("                    location.reload();\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => console.error('Error:', error));\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        resDateInput.addEventListener('change', function() {\r\n");
      out.write("            const selectedDate = this.value;\r\n");
      out.write("            if (!selectedDate) return;\r\n");
      out.write("            \r\n");
      out.write("            // 날짜 수동 입력 변경 시 과거 날짜인지 한 번 더 검증\r\n");
      out.write("            if (selectedDate < todayStr) {\r\n");
      out.write("                alert(\"과거 날짜는 예약할 수 없습니다.\");\r\n");
      out.write("                this.value = \"\";\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            const roomId = document.getElementById(\"roomId\").value;\r\n");
      out.write("\r\n");
      out.write("            fetch('checkReservedTime.do?roomId=' + roomId + '&resDate=' + selectedDate)\r\n");
      out.write("                .then(response => response.json())\r\n");
      out.write("                .then(reservedTimes => {\r\n");
      out.write("                    selectedTimes = []; \r\n");
      out.write("                    timeButtons.forEach(btn => { btn.disabled = false; btn.classList.remove('active'); });\r\n");
      out.write("                    \r\n");
      out.write("                    clearInterval(timerInterval);\r\n");
      out.write("                    document.getElementById(\"timerBox\").style.display = \"none\";\r\n");
      out.write("                    document.getElementById(\"submitBtn\").disabled = true;\r\n");
      out.write("                    document.getElementById(\"holdBtn\").style.display = \"block\";\r\n");
      out.write("                    document.getElementById(\"resNo\").value = \"\";\r\n");
      out.write("\r\n");
      out.write("                    // 현재 시간 구하기 (오늘 날짜를 선택했을 때만 비교하기 위해)\r\n");
      out.write("                    const now = new Date();\r\n");
      out.write("                    const isToday = (selectedDate === todayStr); \r\n");
      out.write("                    const currentHour = now.getHours();\r\n");
      out.write("\r\n");
      out.write("                    timeButtons.forEach(btn => {\r\n");
      out.write("                        const btnTime = btn.getAttribute('data-time');\r\n");
      out.write("                        const btnHour = parseInt(btnTime.split(':')[0]);\r\n");
      out.write("\r\n");
      out.write("                        // 1. 이미 다른 사람이 예약한 시간 비활성화\r\n");
      out.write("                        if (reservedTimes.includes(btnTime)) {\r\n");
      out.write("                            btn.disabled = true;\r\n");
      out.write("                        }\r\n");
      out.write("                        // 2. 오늘 날짜이면서, 현재 시간보다 과거인 버튼 비활성화\r\n");
      out.write("                        else if (isToday && btnHour <= currentHour) {\r\n");
      out.write("                            btn.disabled = true;\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => console.error('Error:', error));\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("        if (!document.getElementById(\"resNo\").value) { alert(\"예약 시간을 먼저 지정해 주세요.\"); return false; }\r\n");
      out.write("        if (!document.getElementById(\"purpose\").value.trim()) { alert(\"사용 목적을 기재해 주세요.\"); return false; }\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"reserve-container\">\r\n");
      out.write("		<h2>\r\n");
      out.write("			회의실 예약 신청\r\n");
      out.write("			");

			if ("Y".equals(loginEmp.getManager())) {
			
      out.write("\r\n");
      out.write("			<button type=\"button\" class=\"btn-modify\"\r\n");
      out.write("				onclick=\"location.href='roomUpdate.do?roomId=");
      out.print(roomInfo.getRoomId());
      out.write("'\">\r\n");
      out.write("				정보 수정</button>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</h2>\r\n");
      out.write("		");

		// 방 예약 가능 여부를 변수로 저장
		boolean isRoomEnable = "Y".equals(roomInfo.getEnable());
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"info-box\">\r\n");
      out.write("			<h3>\r\n");
      out.write("				");
      out.print(roomInfo.getRoomName());
      out.write("\r\n");
      out.write("				");

				if (isRoomEnable) {
				
      out.write("\r\n");
      out.write("				<span class=\"status-badge bg-success\"\r\n");
      out.write("					style=\"font-size: 12px; margin-left: 8px;\">예약 가능</span>\r\n");
      out.write("				");

				} else {
				
      out.write("\r\n");
      out.write("				<span class=\"status-badge bg-danger\"\r\n");
      out.write("					style=\"font-size: 12px; margin-left: 8px;\">점검 중 (예약 불가)</span>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</h3>\r\n");
      out.write("			<p>\r\n");
      out.write("				수용 인원: ");
      out.print(roomInfo.getCapacity());
      out.write("명 | 빔프로젝터: ");
      out.print(roomInfo.getHasBeam());
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("			<p>");
      out.print(roomInfo.getDescription());
      out.write("</p>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"timer-box\" id=\"timerBox\">\r\n");
      out.write("			<span id=\"holdTimeText\"\r\n");
      out.write("				style=\"color: #495057; font-size: 14px; font-weight: bold;\"></span><br>\r\n");
      out.write("			해당 시간대 확보 완료. 남은 시간 내에 확정해 주세요. <span class=\"timer-text\"\r\n");
      out.write("				id=\"timeDisplay\">05:00</span>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"reserveProcess.do\" method=\"post\"\r\n");
      out.write("			onsubmit=\"return validateForm();\">\r\n");
      out.write("			<input type=\"hidden\" id=\"resNo\" name=\"resNo\" value=\"\"> <input\r\n");
      out.write("				type=\"hidden\" id=\"roomId\" name=\"roomId\"\r\n");
      out.write("				value=\"");
      out.print(roomInfo.getRoomId());
      out.write("\"> <input type=\"hidden\"\r\n");
      out.write("				id=\"empNo\" name=\"empNo\" value=\"");
      out.print(loginEmp.getEmpNo());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label>예약 일자</label> <input type=\"date\" id=\"resDate\" name=\"resDate\"\r\n");
      out.write("					required>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label>예약 시간 선택</label>\r\n");
      out.write("				<div class=\"time-grid\" id=\"timeGrid\">\r\n");
      out.write("					");

					// 방이 비활성화 상태면 버튼들에 들어갈 disabled 속성 텍스트 준비
					String disabledAttr = isRoomEnable ? "" : "disabled";
					
      out.write("\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"09:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">09:00</button>\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"10:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">10:00</button>\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"11:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">11:00</button>\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"12:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">12:00</button>\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"13:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">13:00</button>\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"14:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">14:00</button>\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"15:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">15:00</button>\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"16:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">16:00</button>\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"17:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">17:00</button>\r\n");
      out.write("					<button type=\"button\" class=\"time-btn\" data-time=\"18:00\"\r\n");
      out.write("						");
      out.print(disabledAttr);
      out.write(">18:00</button>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<button type=\"button\" class=\"btn-action btn-hold\" id=\"holdBtn\"\r\n");
      out.write("					");
      out.print(disabledAttr);
      out.write(' ');
if (!isRoomEnable) {
      out.write("\r\n");
      out.write("					style=\"background-color: #6c757d; cursor: not-allowed;\" ");
}
      out.write(">\r\n");
      out.write("					선택 시간 확보</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label>사용 목적</label> <input type=\"text\" id=\"purpose\" name=\"purpose\"\r\n");
      out.write("					placeholder=\"예: 주간 부서 회의\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"btn-group\">\r\n");
      out.write("				<a href=\"main.jsp\" class=\"btn-action btn-cancel\" style=\"text-align: center; text-decoration: none; line-height: normal; display: inline-flex; align-items: center; justify-content: center;\">취소</a>\r\n");
      out.write("				<button type=\"submit\" class=\"btn-action btn-submit\" id=\"submitBtn\"\r\n");
      out.write("					disabled>예약 확정</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
