/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-12 00:57:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cookie;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.*;

public final class makeCookie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("	Cookie\r\n");
      out.write("		- 웹 브라우저가 보관하고 있는 데이터로써 웹서버에 요청을 보낼때 함께 전송함\r\n");
      out.write("		\r\n");
      out.write("	Cookie의 동작 방식\r\n");
      out.write("	\r\n");
      out.write("	1.생성단계\r\n");
      out.write("		쿠키를 사용하기 위해 먼저 쿠기를 생성해야함\r\n");
      out.write("		jsp페이지에서 웹서에 쿠키를 생성하고, 자바스크립트를 사용해서 사용자측에서 쿠키를 생성함, \r\n");
      out.write("		이렇게 생성된 쿠키는 응답데이터와 함께 서버로 전송됨\r\n");
      out.write("		\r\n");
      out.write("	2.저장단계\r\n");
      out.write("		웹 브라우저는 응답데이터에 포함된 쿠키를 쿠키 저장소에 보관\r\n");
      out.write("		쿠키는 종류에 따라 메모리나 파일에 저장됨\r\n");
      out.write("		\r\n");
      out.write("	3.전송단계\r\n");
      out.write("		웹 브라우저에서 한번 저장된 쿠키를 매번 요청이 있을때 마다\r\n");
      out.write("		웹 서버에 전송됨.\r\n");
      out.write("		웹 서버는 웹 브라우저가 전송한 쿠키를 사용해서 필요한 작업을 수행함.\r\n");
      out.write("		\r\n");
      out.write("	쿠키의 특성\r\n");
      out.write("		1. 쿠키는 특정 웹 사이트에 접속할때 생성되는 정보를 담은 임시 파일로 크기는 4kb이하로 생성 됨.\r\n");
      out.write("		2. 쿠키는 웹 브라우저가 거쳐간 웹사이트 및 개인정보가 기록되기 때문에\r\n");
      out.write("			개인의 사생활을 침해할 소지가 있음.\r\n");
      out.write("		3. 보안문제를 유발하기 때문에 웹브라우저 자체에 쿠키 거부 기능이 드렁있음\r\n");
      out.write("		4. 쿠키 거부 기능이 웹 브라우저에 설정되어 있으면 쿠키 본래의 목적인 \r\n");
      out.write("			웹 브라우저와 의 연결을 지속시키는 기능을 수행할 수 없다.\r\n");
      out.write("	쿠키의 구성요소\r\n");
      out.write("	 	1. 이름		: 각각의 쿠키를 구별하는 데 사용되는 이름\r\n");
      out.write("	 	2. 값		: 쿠키의 이름과 관련된 값\r\n");
      out.write("	 	3. 유효시간	: 쿠키를 유지하는 시간\r\n");
      out.write("	 	4. 도메인	: 쿠키를 전송할 도메인\r\n");
      out.write("	 	5. 경로		: 쿠키를 전송할 요청 경로\r\n");
      out.write("	 	\r\n");
      out.write("	 쿠키 이름 정의 규칙\r\n");
      out.write("	  1. 쿠키의 이름은 아스키코드의 알파벳과 숫자만을 포함할 수 있다.\r\n");
      out.write("	  2. 콤마, 세미콜론, 공백 등의 문자를 포함 할 수 없다.\r\n");
      out.write("	  3. $로 시작불가능\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
 
	//쿠키 생성 
	Cookie cookie = new Cookie("name", URLEncoder.encode("사람이름", "utf-8"));
	response.addCookie(cookie);

      out.write("\r\n");
      out.write("<!DOCTYPE html><html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Cookie</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.print(cookie.getName() );
      out.write("쿠키의 값 = ");
      out.print(cookie.getValue());
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
